name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow when you push a new tag like v1.0.0

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'  # Set your Go version here

      - name: Build binaries
        run: |
          mkdir -p dist
          platforms=("linux/amd64" "linux/arm64" "linux/arm" "darwin/amd64" "darwin/arm64" "windows/amd64" "windows/arm64")
          for platform in "${platforms[@]}"
          do
            OS=$(echo $platform | cut -d'/' -f1)
            ARCH=$(echo $platform | cut -d'/' -f2)
            OUTPUT_NAME="externalsecret-watcher-${OS}-${ARCH}"
            if [ "$OS" = "windows" ]; then
              OUTPUT_NAME="${OUTPUT_NAME}.exe"
            fi
            echo "Building $OUTPUT_NAME"
            env GOOS=$OS GOARCH=$ARCH CGO_ENABLED=0 go build -o "dist/$OUTPUT_NAME" main.go
          done

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
